/* auto-generated by zig-addon */
/* eslint-disable */

export interface finalizer_stats__struct_28430 {
  external: number
  classes: number
  complete: boolean
}

export interface Person {
  name: string
  age: number
  is_student: boolean
}

export interface OptionalPerson {
  name: string
  age?: number
  is_student?: boolean
}

export interface NestedPayload {
  title: string
  values: Array<number>
  tuple: [number, boolean, string]
  maybe?: string
}

export interface BigInt {
  env?: unknown
  raw?: unknown
  type: number
}

// Opaque host buffer; use the native buffer API to access its bytes.
export type Buffer = object

export interface AsyncInput {
  label: string
  values: Array<number>
}

export interface AsyncSummary {
  label: string
  count: number
  total: number
}

export interface CustomDeinitSummary {
  borrowed_input_marker: string
  borrowed_result_marker: string
  owned_label: string
  label_len: number
}

export interface CountProgress {
  current: number
  total: number
}

export interface AbortSignal {
  aborted: boolean
  reason?: any
  onabort: null | ((this: AbortSignal, event: any) => void)
  addEventListener(name: string, listener: (this: AbortSignal, event: any) => any): void
  removeEventListener(name: string, listener: (this: AbortSignal, event: any) => any): void
  throwIfAborted?(): void
}


export declare function leak_tracker_start(): void
export declare function leak_tracker_finish(): boolean
export declare function leak_tracker_live_bytes(): number
export declare function leak_tracker_abort(): void
export declare function tracked_alloc_roundtrip(len: number): boolean
export declare function begin_finalizer_state_check(external_count: number, class_count: number): void
export declare function finalizer_stats(): finalizer_stats__struct_28430
export declare function hello(name: string): string
export declare function get_object(config: Person): Person
export declare function get_optional_object(config: OptionalPerson): OptionalPerson
export declare function nullable_name_is_null(name: string | undefined | null): boolean
export declare function get_named_array(array: [number, boolean, string]): [number, boolean, string]
export declare function array_sum(values: Array<number>): number
export declare function arraylist_sum(values: Array<number>): number
export declare function nested_summary(payload: NestedPayload): number
export declare function union_kind(value: number | string): string
export declare function create_function(): (arg0: number, arg1: number) => number
export declare function call_function(cb: (arg0: number, arg1: number) => number): number
export declare function call_function_with_reference(cb: (arg0: number, arg1: number) => number): number
export declare function function_reference_ref_count(cb: (arg0: number, arg1: number) => number): number
export declare function create_bigint_value(): BigInt
export declare function create_small_bigint_value(): BigInt
export declare function bigint_to_i64(value: BigInt): number
export declare function manual_resolved_promise(): Promise<unknown>
export declare function create_buffer_copy(len: number): Buffer
export declare function create_buffer_new(len: number): Buffer
export declare function create_external_buffer(len: number): Buffer
export declare function buffer_length(value: Buffer): number
export declare function buffer_first_byte(value: Buffer): number
export declare function create_arraybuffer_copy(len: number): ArrayBuffer
export declare function create_arraybuffer_new(len: number): ArrayBuffer
export declare function create_external_arraybuffer(len: number): ArrayBuffer
export declare function arraybuffer_length(value: ArrayBuffer): number
export declare function arraybuffer_first_byte(value: ArrayBuffer): number
export declare function create_uint8_typedarray_copy(): Uint8Array
export declare function create_int16_typedarray_copy(): Int16Array
export declare function create_uint16_typedarray_copy(): Uint16Array
export declare function create_int32_typedarray_copy(): Int32Array
export declare function create_uint32_typedarray_copy(): Uint32Array
export declare function create_float64_typedarray_copy(): Float64Array
export declare function create_external_uint8_typedarray(): Uint8Array
export declare function typedarray_sum(value: Uint8Array): number
export declare function int16_typedarray_sum(value: Int16Array): number
export declare function uint16_typedarray_sum(value: Uint16Array): number
export declare function int32_typedarray_sum(value: Int32Array): number
export declare function uint32_typedarray_sum(value: Uint32Array): number
export declare function float32_typedarray_sum(value: Float32Array): number
export declare function float64_typedarray_sum(value: Float64Array): number
export declare function create_dataview_copy(): DataView
export declare function create_dataview_new(len: number): DataView
export declare function create_external_dataview(): DataView
export declare function dataview_length(value: DataView): number
export declare function dataview_uint32_le(value: DataView): number
export declare function dataview_accessors_roundtrip(): boolean
export declare function invalid_typedarray_from_arraybuffer(): void
export declare function invalid_dataview_from_arraybuffer(): void
export declare function reset_external_finalizer_counts(): void
export declare function external_finalizer_count(): number
export declare class MemoryClass {
  constructor(name: string, values: Array<number>)
  name: string
  values: Array<number>
  total(): number
}

export declare class MemoryClassWithoutInit {
  private constructor()
  count: number
  static make(): MemoryClassWithoutInit
  total(): number
}

export declare class MemoryFactoryClass {
  constructor(name: string, values: Array<number>)
  name: string
  values: Array<number>
  static initWithFactory(name: string, values: Array<number>): MemoryFactoryClass
  total(): number
}

export declare function reset_class_finalizer_count(): void
export declare function class_finalizer_count(): number
export declare function memory_async_summary(input: AsyncInput): Promise<AsyncSummary>
export declare function memory_async_summary_single(input: AsyncInput): Promise<AsyncSummary>
export declare function memory_async_custom_deinit(label: string): Promise<CustomDeinitSummary>
export declare function memory_async_custom_deinit_single(label: string): Promise<CustomDeinitSummary>
export declare function memory_async_custom_deinit_reset(): void
export declare function memory_async_custom_input_deinit_count(): number
export declare function memory_async_custom_result_deinit_count(): number
export declare function memory_async_void(label: string): Promise<void>
export declare function memory_async_fail(message: string): Promise<void>
export declare function memory_async_progress(total: number, onEvent?: (event: CountProgress) => void): Promise<number>
export declare function memory_event_mode_progress(total: number, onEvent?: (event: CountProgress) => void): Promise<number>
export declare function memory_abortable_count(total: number, signal: AbortSignal): Promise<number>
export declare function memory_abortable_slow_count(total: number, signal: AbortSignal): Promise<number>
export declare function memory_worker(value: number): Promise<unknown>
export declare function memory_thread_safe_function(tsfn: (err: Error | null, arg0: number, arg1: number) => number): void
