const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { test } = require("node:test");
const renameProject = require("../bin/rename-project.cjs");

test("rename moves native loaders and declarations with nested package entry points", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "zig-napi-rename-"));
  try {
    const original = {
      name: "@scope/old",
      napi: { binaryName: "old", packageName: "@scope/old" },
      main: "old.cjs",
      types: "old.d.ts",
      exports: { ".": { types: "./old.d.ts", require: "./old.cjs", import: "./old.mjs" } },
      imports: { "#binding": "./old.cjs" },
      browser: { "./old.cjs": "./old.wasi-browser.js", "node:fs": false },
      files: ["old.cjs", "old.d.ts", "*.node"],
      optionalDependencies: { "@scope/old-linux-x64-gnu": "1.0.0" },
    };
    fs.writeFileSync(path.join(directory, "package.json"), JSON.stringify(original));
    fs.writeFileSync(path.join(directory, "build.zig"), '.{ .name = "old" }');
    fs.writeFileSync(
      path.join(directory, "old.cjs"),
      '// auto-generated by NAPI-RS\nmodule.exports = require("./old.linux-x64-gnu.node");',
    );
    for (const name of ["old.d.ts", "old.mjs", "old.wasi-browser.js", "old.linux-x64-gnu.node"])
      fs.writeFileSync(path.join(directory, name), "fixture");
    const flags = { binaryName: "new", packageName: "@scope/new" };
    renameProject(directory, flags);
    const metadata = JSON.parse(fs.readFileSync(path.join(directory, "package.json")));
    assert.deepEqual(metadata.exports["."], {
      types: "./new.d.ts",
      require: "./new.cjs",
      import: "./new.mjs",
    });
    assert.deepEqual(metadata.browser, { "./new.cjs": "./new.wasi-browser.js", "node:fs": false });
    assert.equal(metadata.imports["#binding"], "./new.cjs");
    assert.equal(metadata.optionalDependencies["@scope/new-linux-x64-gnu"], "1.0.0");
    assert.match(
      fs.readFileSync(path.join(directory, "new.cjs"), "utf8"),
      /new\.linux-x64-gnu\.node/,
    );
    for (const file of ["new.d.ts", "new.mjs", "new.wasi-browser.js", "new.linux-x64-gnu.node"])
      assert.ok(fs.existsSync(path.join(directory, file)), file);
  } finally {
    fs.rmSync(directory, { recursive: true, force: true });
  }
});

test("rename collision fails before changing any metadata or sources", () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "zig-napi-rename-collision-"));
  try {
    const source = JSON.stringify({ name: "old", napi: { binaryName: "old" }, types: "old.d.ts" });
    fs.writeFileSync(path.join(directory, "package.json"), source);
    fs.writeFileSync(path.join(directory, "old.d.ts"), "old");
    fs.writeFileSync(path.join(directory, "new.d.ts"), "keep");
    assert.throws(
      () => renameProject(directory, { binaryName: "new", packageName: "new" }),
      /already exists/,
    );
    assert.equal(fs.readFileSync(path.join(directory, "package.json"), "utf8"), source);
    assert.equal(fs.readFileSync(path.join(directory, "old.d.ts"), "utf8"), "old");
    assert.equal(fs.readFileSync(path.join(directory, "new.d.ts"), "utf8"), "keep");
  } finally {
    fs.rmSync(directory, { recursive: true, force: true });
  }
});
