/* auto-generated by zig-addon */
/* eslint-disable */

// Opaque host buffer; use the native buffer API to access its bytes.
export type Buffer = object


export declare function allocator_kind(): string
export declare function manual_allocation_roundtrip(len: number): boolean
export declare function make_js_owned_buffer(len: number): Buffer
export declare function make_copied_buffer(): Buffer
export declare function input_sum(input: Buffer): number
