/* eslint-disable */
/* auto-generated by zig-napi */

const __nodeFs = require("node:fs");
const __nodePath = require("node:path");
const { WASI: __nodeWASI } = require("node:wasi");
const { Worker } = require("node:worker_threads");

const {
  emnapiAsyncWorkPlugin: __emnapiAsyncWorkPlugin,
  emnapiTSFNPlugin: __emnapiTSFNPlugin,
  createOnMessage: __wasmCreateOnMessageForFsProxy,
  instantiateNapiModuleSync: __emnapiInstantiateNapiModuleSync,
} = require("@napi-rs/wasm-runtime");
const { createContext: __emnapiCreateContext } = require("@emnapi/runtime");

function __getWasiWorkerExecArgv() {
  const __workerExecArgv = [];
  for (let index = 0; index < process.execArgv.length; index += 1) {
    const arg = process.execArgv[index];
    if (
      arg === "--input-type" ||
      arg === "--eval" ||
      arg === "-e" ||
      arg === "--print" ||
      arg === "-p"
    ) {
      index += 1;
      continue;
    }
    if (
      arg.startsWith("--input-type=") ||
      arg.startsWith("--eval=") ||
      arg.startsWith("--print=")
    ) {
      continue;
    }
    __workerExecArgv.push(arg);
  }
  return __workerExecArgv;
}

function __isInvalidWasiWorkerExecArgv(errorMessage, argument) {
  const equalsIndex = argument.indexOf("=");
  const argumentName = equalsIndex === -1 ? argument : argument.slice(0, equalsIndex);
  return (
    errorMessage.includes(": " + argumentName + ",") ||
    errorMessage.includes(": " + argumentName + "=") ||
    errorMessage.endsWith(": " + argumentName) ||
    errorMessage.includes(", " + argumentName + ",") ||
    errorMessage.includes(", " + argumentName + "=") ||
    errorMessage.endsWith(", " + argumentName)
  );
}

function __removeInvalidWasiWorkerExecArgv(execArgv, error) {
  if (typeof error.message !== "string") {
    return;
  }
  const __workerExecArgv = [];
  let removed = false;
  for (let index = 0; index < execArgv.length; index += 1) {
    const arg = execArgv[index];
    if (arg.startsWith("-") && __isInvalidWasiWorkerExecArgv(error.message, arg)) {
      removed = true;
      if (
        !arg.includes("=") &&
        index + 1 < execArgv.length &&
        !execArgv[index + 1].startsWith("-")
      ) {
        index += 1;
      }
      continue;
    }
    __workerExecArgv.push(arg);
  }
  return removed ? __workerExecArgv : undefined;
}

function __createWasiWorker(filename) {
  let __workerExecArgv = __getWasiWorkerExecArgv();
  for (;;) {
    try {
      return new Worker(filename, {
        env: process.env,
        execArgv: __workerExecArgv,
        workerData: { hostRoot: __hostRoot, rootDir: __rootDir },
      });
    } catch (error) {
      if (!error || error.code !== "ERR_WORKER_INVALID_EXEC_ARGV") {
        throw error;
      }
      const nextWorkerExecArgv = __removeInvalidWasiWorkerExecArgv(__workerExecArgv, error);
      if (!nextWorkerExecArgv) {
        throw error;
      }
      __workerExecArgv = nextWorkerExecArgv;
    }
  }
}

const __cwd = process.cwd();
const __rootDir = __nodePath.parse(__cwd).root;
// Android has no writable filesystem root, so the preopened root is the cwd.
const __hostRoot = process.platform === "android" ? __cwd : __rootDir;

const __wasi = new __nodeWASI({
  version: "preview1",
  env: process.env,
  preopens: {
    [__rootDir]: __hostRoot,
    [__hostRoot]: __hostRoot,
  },
});

const __sharedMemory = new WebAssembly.Memory({
  initial: 4000,
  maximum: 65536,
  shared: true,
});
const __DEFAULT_ASYNC_WORK_POOL_SIZE = 4;
const __MAX_ASYNC_WORK_POOL_SIZE = 64;

function __normalizeWorkerCount(value, defaultValue, maxValue) {
  if (!Number.isFinite(value) || !Number.isInteger(value) || value <= 0 || value > maxValue) {
    return defaultValue;
  }
  return value;
}

function __warnInvalidWorkerCount(value, fallback) {
  const message = "zig-napi: ignoring invalid worker pool size " + value + "; using " + fallback;
  if (
    typeof process === "object" &&
    process !== null &&
    typeof process.emitWarning === "function"
  ) {
    process.emitWarning(message);
    return;
  }
  globalThis.console?.warn?.(message);
}

const __asyncWorkPoolSize = (function () {
  const configured = Number(
    process.env.NAPI_RS_ASYNC_WORK_POOL_SIZE ?? process.env.UV_THREADPOOL_SIZE,
  );
  // Unset (NaN) and an explicit 0 both mean "use the default"; anything else
  // has to be a finite, positive, bounded integer.
  if (Number.isNaN(configured) || configured === 0) {
    return __DEFAULT_ASYNC_WORK_POOL_SIZE;
  }
  const normalized = __normalizeWorkerCount(
    configured,
    __DEFAULT_ASYNC_WORK_POOL_SIZE,
    __MAX_ASYNC_WORK_POOL_SIZE,
  );
  if (normalized !== configured) {
    __warnInvalidWorkerCount(configured, normalized);
  }
  return normalized;
})();

const __wasmCandidates = [
  __nodePath.join(__dirname, "conversion_audit.wasm32-wasi.debug.wasm"),
  __nodePath.join(__dirname, "conversion_audit.wasm32-wasi.wasm"),
  __nodePath.join(__dirname, "zig-out", "node", "conversion_audit.wasm32-wasi.debug.wasm"),
  __nodePath.join(__dirname, "zig-out", "node", "conversion_audit.wasm32-wasi.wasm"),
];

// The packaged artifact lives in the optional <package>-<platformArchABI>
// package. Its entry point may sit in a subdirectory, so the artifact is
// searched from the entry directory up to the package root before falling back
// to resolving the artifact as a subpath (packages without an entry point).
function __resolvePackagedWasmPath() {
  const __wasmName = "conversion_audit.wasm32-wasi.wasm";
  try {
    const __entry = require.resolve("zig-napi-node-test-wasm32-wasi");
    let __directory = __nodePath.dirname(__entry);
    for (;;) {
      const __candidate = __nodePath.join(__directory, __wasmName);
      if (__nodeFs.existsSync(__candidate)) {
        return __candidate;
      }
      const __parent = __nodePath.dirname(__directory);
      if (__parent === __directory) {
        break;
      }
      __directory = __parent;
    }
  } catch {}
  try {
    return require.resolve("zig-napi-node-test-wasm32-wasi/conversion_audit.wasm32-wasi.wasm");
  } catch {}
  return undefined;
}

let __wasmFilePath = __wasmCandidates.find((candidate) => __nodeFs.existsSync(candidate));

if (!__wasmFilePath) {
  __wasmFilePath = __resolvePackagedWasmPath();
}

if (!__wasmFilePath) {
  throw new Error(
    "Cannot find conversion_audit.wasm32-wasi.wasm next to this loader, in zig-out/node, or in the zig-napi-node-test-wasm32-wasi package.",
  );
}

const __wasmFile = __nodeFs.readFileSync(__wasmFilePath);
let __emnapiContext;

const __wasiDisposeSymbol = Symbol.for("napi.rs.wasi.dispose");
const __wasiWorkers = new Set();
let __napiInstance;
let __emnapiContextDestroyed = false;
let __emnapiContextDestroyPromise;
let __emnapiWasmEnvCleanupPrepared = false;
let __emnapiWasmEnvCleanupRan = false;
let __emnapiWasmEnvCleanupDrained = false;
let __emnapiWasmEnvCleanupDrainPromise;
let __wasiDisposed = false;
let __wasiDisposePromise;
let __completeWasiDisposal = function () {};
// Overridden by loader flavors that have a last-resort reclaim for a rollback
// that stopped short of destroying the context.
let __retainWasiRollbackForRetry = function () {};

function __isThenable(value) {
  return (
    value !== null &&
    (typeof value === "object" || typeof value === "function") &&
    typeof value.then === "function"
  );
}

function __createCleanupError(errors, message) {
  if (errors.length === 1) {
    return errors[0];
  }
  const __AggregateError = globalThis.AggregateError;
  if (typeof __AggregateError === "function") {
    return new __AggregateError(errors, message);
  }
  const error = new Error(message);
  error.errors = errors;
  return error;
}

function __attachCleanupErrors(error, cleanupErrors) {
  if (cleanupErrors.length === 0) {
    return error;
  }
  const cleanupError = __createCleanupError(cleanupErrors, "WASI binding cleanup failed");
  try {
    if (error && (typeof error === "object" || typeof error === "function")) {
      if (error.cause === undefined) {
        error.cause = cleanupError;
        if (error.cause === cleanupError) {
          return error;
        }
      }
      if (Array.isArray(error.cleanupErrors)) {
        error.cleanupErrors.push(cleanupError);
        return error;
      }
      const attachedCleanupErrors = [cleanupError];
      error.cleanupErrors = attachedCleanupErrors;
      if (error.cleanupErrors === attachedCleanupErrors) {
        return error;
      }
    }
  } catch {}
  const aggregate = __createCleanupError(
    [error, cleanupError],
    "WASI binding initialization and cleanup failed",
  );
  try {
    aggregate.cause = error;
  } catch {}
  return aggregate;
}

function __prepareWasmEnvCleanup() {
  if (__emnapiWasmEnvCleanupPrepared) {
    return;
  }
  const prepare = __napiInstance?.exports?.napi_prepare_wasm_env_cleanup;
  if (typeof prepare === "function") {
    prepare();
    __emnapiWasmEnvCleanupRan = true;
  }
  __emnapiWasmEnvCleanupPrepared = true;
}

// Mirror the primitive @emnapi/core schedules its threadsafe-function dispatch
// on, so the drain turns below interleave with that dispatch instead of racing
// ahead of it on a faster queue.
const __scheduleMacrotask = (function () {
  if (typeof setImmediate === "function") {
    return function (callback) {
      setImmediate(callback);
    };
  }
  const __MessageChannel = globalThis.MessageChannel;
  if (typeof __MessageChannel === "function") {
    return function (callback) {
      const channel = new __MessageChannel();
      channel.port1.onmessage = function () {
        channel.port1.onmessage = null;
        try {
          channel.port1.close();
        } catch {}
        try {
          channel.port2.close();
        } catch {}
        callback();
      };
      channel.port2.postMessage(null);
    };
  }
  return function (callback) {
    setTimeout(callback, 0);
  };
})();

// Turns to wait for while the addon still reports queued settlements. Reaching
// zero is the only success; a counter still nonzero at this bound rejects the
// disposal as retryable (ERR_NAPI_WASI_CLEANUP_PENDING) instead of destroying
// the context over a still-queued settlement.
const __WASM_ENV_CLEANUP_DRAIN_TURNS = 128;
// Without napi_wasm_env_cleanup_pending the queue is not observable. Fall back
// to the number of turns @emnapi/core needs to coalesce and dispatch a call
// made on this thread (two), plus a margin.
const __WASM_ENV_CLEANUP_BLIND_DRAIN_TURNS = 4;

function __drainWasmEnvCleanup() {
  if (__emnapiWasmEnvCleanupDrained || !__emnapiWasmEnvCleanupRan) {
    return;
  }
  if (__emnapiWasmEnvCleanupDrainPromise) {
    return __emnapiWasmEnvCleanupDrainPromise;
  }
  const pending = __napiInstance?.exports?.napi_wasm_env_cleanup_pending;
  const observable = typeof pending === "function";
  if (observable) {
    // A probe that throws is not proof that the queue is empty - a getter or a
    // trap can throw for any reason - so the error is propagated unchanged and
    // the drain stays unset, which keeps disposal retryable. Only an export
    // that is absent at all falls back to the bounded blind wait below.
    const queued = pending();
    if (!queued) {
      __emnapiWasmEnvCleanupDrained = true;
      return;
    }
  }
  const limit = observable ? __WASM_ENV_CLEANUP_DRAIN_TURNS : __WASM_ENV_CLEANUP_BLIND_DRAIN_TURNS;
  const drainPromise = (async () => {
    let queued = 0;
    for (let turn = 0; turn < limit; turn++) {
      await new Promise((resolve) => {
        __scheduleMacrotask(resolve);
      });
      if (!observable) {
        continue;
      }
      // Same rule as the first probe: a throwing probe rejects the drain (the
      // caller keeps the context and can retry) instead of being read as an
      // empty queue.
      queued = pending();
      if (!queued) {
        return;
      }
    }
    if (!observable) {
      // Blind wait: without napi_wasm_env_cleanup_pending the bound IS the
      // contract - there is nothing to consult, so finishing the turns is
      // finishing the drain.
      return;
    }
    // Claiming success here would be indistinguishable from the stranding this
    // drain exists to prevent: disposal would go on to destroy the context,
    // whose cleanup hook discards the still-queued settlement with a null env.
    // Reject as a retryable cleanup failure instead - the drained flag stays
    // unset, nothing is destroyed, and a later dispose() drains again by which
    // time the queue has usually been delivered.
    const drainError = new Error(
      "the wasm environment still reports " +
        queued +
        " queued settlement(s) after " +
        limit +
        " event-loop turns; the context was not destroyed - retry dispose() to wait for the queue again",
    );
    drainError.code = "ERR_NAPI_WASI_CLEANUP_PENDING";
    throw drainError;
  })().then(
    (value) => {
      // Set only when the wait actually finished AND the queue was seen empty
      // (or is unobservable): a drain that timed out rejects above and must
      // stay repeatable.
      __emnapiWasmEnvCleanupDrained = true;
      __emnapiWasmEnvCleanupDrainPromise = undefined;
      return value;
    },
    (error) => {
      __emnapiWasmEnvCleanupDrainPromise = undefined;
      throw error;
    },
  );
  __emnapiWasmEnvCleanupDrainPromise = drainPromise;
  return drainPromise;
}

function __destroyEmnapiContext() {
  if (__emnapiContextDestroyed || __emnapiContext === undefined) {
    __emnapiContextDestroyed = true;
    return;
  }
  if (__emnapiContextDestroyPromise) {
    return __emnapiContextDestroyPromise;
  }
  // Context.destroy() disables JS before cleanup hooks run, so settle what the
  // barrier queued while this environment can still call JavaScript.
  __prepareWasmEnvCleanup();
  const result = __emnapiContext.destroy();
  if (!__isThenable(result)) {
    __emnapiContextDestroyed = true;
    return;
  }
  const destroyPromise = Promise.resolve(result).then(
    (value) => {
      __emnapiContextDestroyed = true;
      return value;
    },
    (error) => {
      __emnapiContextDestroyPromise = undefined;
      throw error;
    },
  );
  __emnapiContextDestroyPromise = destroyPromise;
  return destroyPromise;
}

function __terminateWasiWorkers() {
  const cleanupErrors = [];
  const pending = [];
  for (const worker of __wasiWorkers) {
    let result;
    try {
      // Pooled workers are owned by the emnapi wasm-threads manager once it
      // loads them, and in Node that manager treats any exit it did not
      // bookkeep as a crash: its exit handler throws "Worker stopped with exit
      // code 1", which is exactly what terminate() reports. Disposal is a
      // deliberate shutdown of the whole pool, so drop that crash detector for
      // the workers being terminated here - a worker that really crashed earlier
      // still surfaced through it while the addon was alive.
      worker.removeAllListeners?.("exit");
      result = worker.terminate();
    } catch (error) {
      cleanupErrors.push(error);
      continue;
    }
    if (__isThenable(result)) {
      pending.push(
        Promise.resolve(result).then(
          () => {
            __wasiWorkers.delete(worker);
          },
          (error) => {
            cleanupErrors.push(error);
          },
        ),
      );
    } else {
      __wasiWorkers.delete(worker);
    }
  }
  const finish = () => {
    if (cleanupErrors.length > 0) {
      throw __createCleanupError(cleanupErrors, "Failed to terminate WASI workers");
    }
  };
  return pending.length > 0 ? Promise.all(pending).then(finish) : finish();
}

function __finishWasiDisposal() {
  const workerResult = __terminateWasiWorkers();
  if (__isThenable(workerResult)) {
    return Promise.resolve(workerResult).then(__completeWasiDisposal);
  }
  return __completeWasiDisposal();
}

function __continueWasiDisposal() {
  const destroyResult = __destroyEmnapiContext();
  if (__isThenable(destroyResult)) {
    return Promise.resolve(destroyResult).then(__finishWasiDisposal);
  }
  return __finishWasiDisposal();
}

function __startWasiDisposal() {
  // Run the pre-teardown barrier, let the settlements it queued reach
  // JavaScript, and only then destroy the environment. Doing these two back to
  // back is what strands them.
  __prepareWasmEnvCleanup();
  const drainResult = __drainWasmEnvCleanup();
  if (__isThenable(drainResult)) {
    return Promise.resolve(drainResult).then(__continueWasiDisposal);
  }
  return __continueWasiDisposal();
}

function __disposeWasiBinding() {
  if (__wasiDisposePromise) {
    return __wasiDisposePromise;
  }
  if (__wasiDisposed) {
    return Promise.resolve();
  }
  let resolveDispose;
  let rejectDispose;
  const disposePromise = new Promise((resolve, reject) => {
    resolveDispose = resolve;
    rejectDispose = reject;
  });
  __wasiDisposePromise = disposePromise;
  let result;
  try {
    result = __startWasiDisposal();
  } catch (error) {
    __wasiDisposePromise = undefined;
    rejectDispose(error);
    return disposePromise;
  }
  Promise.resolve(result).then(
    (value) => {
      __wasiDisposed = true;
      resolveDispose(value);
    },
    (error) => {
      __wasiDisposePromise = undefined;
      rejectDispose(error);
    },
  );
  return disposePromise;
}

/**
 * Publishes the disposal hook on the binding exports. Access it with
 * binding[Symbol.for("napi.rs.wasi.dispose")]().
 */
function __publishWasiDispose(exports) {
  Object.defineProperty(exports, __wasiDisposeSymbol, {
    configurable: false,
    enumerable: false,
    value: __disposeWasiBinding,
    writable: false,
  });
}

function __finishWasiInitializationRollback(cleanupErrors) {
  let workerResult;
  try {
    workerResult = __terminateWasiWorkers();
  } catch (cleanupError) {
    cleanupErrors.push(cleanupError);
    return cleanupErrors;
  }
  if (__isThenable(workerResult)) {
    return Promise.resolve(workerResult)
      .catch((cleanupError) => {
        cleanupErrors.push(cleanupError);
      })
      .then(() => cleanupErrors);
  }
  return cleanupErrors;
}

function __destroyContextForWasiRollback(cleanupErrors) {
  let destroyResult;
  try {
    destroyResult = __destroyEmnapiContext();
  } catch (cleanupError) {
    cleanupErrors.push(cleanupError);
    return __finishWasiInitializationRollback(cleanupErrors);
  }
  if (__isThenable(destroyResult)) {
    return Promise.resolve(destroyResult)
      .catch((cleanupError) => {
        cleanupErrors.push(cleanupError);
      })
      .then(() => __finishWasiInitializationRollback(cleanupErrors));
  }
  return __finishWasiInitializationRollback(cleanupErrors);
}

function __retainFailedWasiRollback(cleanupErrors) {
  try {
    __retainWasiRollbackForRetry();
  } catch (cleanupError) {
    cleanupErrors.push(cleanupError);
  }
  return cleanupErrors;
}

/**
 * Initialization can fail after registration has already run, and registration
 * runs with a live environment: a module-init hook can start async work and
 * then return an error, and the promise it created may already have escaped
 * into JavaScript. The barrier cancels that work and queues the settlement, so
 * this path needs the same drain the ordinary disposal does.
 *
 * A barrier or drain that did not finish stops the rollback short of
 * destroying, exactly like dispose() does: destroying would run the cleanup
 * hook that discards the queued settlement with a null env, hanging a promise
 * that nothing could ever settle. The retained context is reclaimed by the
 * flavor's process teardown and can be retried.
 */
function __rollbackWasiInitialization() {
  const cleanupErrors = [];
  let drainResult;
  let settlementsUnreached = false;
  try {
    __prepareWasmEnvCleanup();
    drainResult = __drainWasmEnvCleanup();
  } catch (cleanupError) {
    cleanupErrors.push(cleanupError);
    settlementsUnreached = true;
  }
  if (__isThenable(drainResult)) {
    return Promise.resolve(drainResult).then(
      () => __destroyContextForWasiRollback(cleanupErrors),
      (cleanupError) => {
        cleanupErrors.push(cleanupError);
        return __retainFailedWasiRollback(cleanupErrors);
      },
    );
  }
  if (settlementsUnreached) {
    return __retainFailedWasiRollback(cleanupErrors);
  }
  return __destroyContextForWasiRollback(cleanupErrors);
}

const __wasiRollbackRegistrySymbol = Symbol.for("napi.rs.wasi.rollback.registry.v1");
const __wasiRollbackRegistryKey = typeof __filename === "string" ? __filename : __wasmFilePath;

function __getWasiRollbackRegistry() {
  const existing = process[__wasiRollbackRegistrySymbol];
  if (existing !== undefined) {
    if (!(existing instanceof Map)) {
      throw new TypeError("The process-wide zig-napi WASI rollback registry is invalid");
    }
    return existing;
  }
  const registry = new Map();
  Object.defineProperty(process, __wasiRollbackRegistrySymbol, {
    configurable: false,
    enumerable: false,
    value: registry,
    writable: false,
  });
  return registry;
}

const __wasiRollbackRegistry = __getWasiRollbackRegistry();

const __wasiExitListenerSymbol = Symbol.for("napi.rs.wasi.exitListener.v1");

/**
 * One teardown listener per loader file, tracked process-wide rather than per
 * module instance: a rollback retained by one instance is replayed by the next
 * one (the record is process-wide too), and the replay has to be able to remove
 * the listener the first instance registered. The listener belongs to the
 * instance whose context is retained, which is exactly the context a replay
 * destroys.
 */
function __getWasiExitListenerRegistry() {
  const existing = process[__wasiExitListenerSymbol];
  if (existing !== undefined) {
    if (!(existing instanceof Map)) {
      throw new TypeError("The process-wide zig-napi WASI exit listener registry is invalid");
    }
    return existing;
  }
  const registry = new Map();
  Object.defineProperty(process, __wasiExitListenerSymbol, {
    configurable: false,
    enumerable: false,
    value: registry,
    writable: false,
  });
  return registry;
}

const __wasiExitListenerRegistry = __getWasiExitListenerRegistry();

function __completeWasiInitializationRollback(record, cleanupErrors) {
  try {
    if (cleanupErrors.length === 0) {
      if (__wasiRollbackRegistry.get(__wasiRollbackRegistryKey) === record) {
        __wasiRollbackRegistry.delete(__wasiRollbackRegistryKey);
      }
      // A rollback that finished cleanly has nothing left to reclaim, so the
      // process teardown the retry path registered is removed again. Only a
      // retained record keeps it, so re-requiring this file repeatedly cannot
      // accumulate exit listeners.
      __completeWasiDisposal();
      return;
    }
    record.error = __attachCleanupErrors(record.error, cleanupErrors);
  } catch (cleanupError) {
    try {
      record.error = __createCleanupError(
        [record.error, cleanupError],
        "WASI binding initialization and cleanup failed",
      );
    } catch {}
  } finally {
    record.active = false;
    record.promise = undefined;
  }
}

function __runWasiInitializationRollback(record) {
  if (record.active) {
    return;
  }
  record.active = true;
  let rollbackResult;
  try {
    rollbackResult = record.rollback();
  } catch (cleanupError) {
    __completeWasiInitializationRollback(record, [cleanupError]);
    return;
  }
  if (!__isThenable(rollbackResult)) {
    __completeWasiInitializationRollback(record, rollbackResult);
    return;
  }
  record.promise = Promise.resolve(rollbackResult).then(
    (cleanupErrors) => {
      __completeWasiInitializationRollback(record, cleanupErrors);
    },
    (cleanupError) => {
      __completeWasiInitializationRollback(record, [cleanupError]);
    },
  );
}

let __wasiModule;
let __napiModule;
let __wasiExitListenerRegistered = false;

function __removeWasiExitListener() {
  __wasiExitListenerRegistered = false;
  const listener = __wasiExitListenerRegistry.get(__wasiRollbackRegistryKey);
  if (listener === undefined) {
    return;
  }
  __wasiExitListenerRegistry.delete(__wasiRollbackRegistryKey);
  if (typeof process.removeListener === "function") {
    process.removeListener("exit", listener);
  }
}

function __disposeWasiBindingAtExit() {
  __wasiExitListenerRegistered = false;
  // An "exit" handler cannot yield, so it cannot wait for queued settlements
  // the way __startWasiDisposal does - the process is leaving and those
  // promises have no observer left anyway. Run the synchronous teardown
  // directly; every step is idempotent, which also makes this the synchronous
  // finish for a disposal that is still waiting for its drain.
  try {
    __destroyEmnapiContext();
  } catch {}
  try {
    const workerResult = __terminateWasiWorkers();
    if (__isThenable(workerResult)) {
      void Promise.resolve(workerResult).catch(() => {});
    }
  } catch {}
}

function __registerWasiExitListener() {
  if (typeof process.once !== "function") {
    return;
  }
  __wasiExitListenerRegistered = true;
  if (__wasiExitListenerRegistry.has(__wasiRollbackRegistryKey)) {
    return;
  }
  __wasiExitListenerRegistry.set(__wasiRollbackRegistryKey, __disposeWasiBindingAtExit);
  process.once("exit", __disposeWasiBindingAtExit);
}

__completeWasiDisposal = __removeWasiExitListener;
__retainWasiRollbackForRetry = __registerWasiExitListener;

// A rollback that stopped short of destroying its context keeps the record so
// re-requiring this file replays it instead of re-instantiating. Nothing forces
// that replay, so the context is handed to the same synchronous teardown a
// successful load uses: a process that exits without retrying still runs the
// cleanup hooks. The module setup above has to be complete first, because a
// replay that finishes is what removes that teardown again.
const __pendingWasiRollback = __wasiRollbackRegistry.get(__wasiRollbackRegistryKey);
if (__pendingWasiRollback !== undefined) {
  __runWasiInitializationRollback(__pendingWasiRollback);
  throw __pendingWasiRollback.error;
}

function __captureEmnapiAutoDestroyListener() {
  const __process = process;
  if (
    !__process ||
    typeof __process.prependListener !== "function" ||
    typeof __process.removeListener !== "function"
  ) {
    return;
  }
  let __autoDestroyListener;
  const __captureListener = (__event, __listener) => {
    if (__event === "beforeExit" && __autoDestroyListener === undefined) {
      __autoDestroyListener = __listener;
    }
  };
  try {
    // Run before existing newListener hooks so a hook that registers its own
    // beforeExit listener cannot be mistaken for emnapi's registration.
    __process.prependListener("newListener", __captureListener);
  } catch {
    return;
  }
  return () => {
    try {
      __process.removeListener("newListener", __captureListener);
    } catch {}
    if (__autoDestroyListener !== undefined) {
      try {
        __process.removeListener("beforeExit", __autoDestroyListener);
      } catch {}
    }
  };
}

function __annotateWasiInstantiationError(error) {
  if (error && typeof error.message === "string" && /memory|linkerror/i.test(error.message)) {
    error.message +=
      "\n[zig-napi] " +
      "the loader allocates WebAssembly.Memory(initial: 4000 pages, maximum: 65536 pages, shared: true); the linked wasm must declare the same limits (zig-napi passes -Dwasi-initial-memory-pages / -Dwasi-max-memory-pages from napi.wasm.initialMemory / maximumMemory)";
  }
  return error;
}

try {
  const __finishAutoDestroyCapture = __captureEmnapiAutoDestroyListener();
  try {
    __emnapiContext = __emnapiCreateContext({ autoDestroy: false });
    __emnapiContext.suppressDestroy();
  } finally {
    __finishAutoDestroyCapture?.();
  }

  ({
    instance: __napiInstance,
    module: __wasiModule,
    napiModule: __napiModule,
  } = __emnapiInstantiateNapiModuleSync(__wasmFile, {
    context: __emnapiContext,
    asyncWorkPoolSize: __asyncWorkPoolSize,
    reuseWorker: true,
    plugins: [__emnapiAsyncWorkPlugin, __emnapiTSFNPlugin],
    wasi: __wasi,
    onCreateWorker() {
      const worker = __createWasiWorker(__nodePath.join(__dirname, "wasi-worker.mjs"));
      __wasiWorkers.add(worker);
      worker.onmessage = ({ data }) => {
        __wasmCreateOnMessageForFsProxy(__nodeFs)(data);
      };
      // Pooled workers live as long as the addon does, and Rust threads are
      // never joined, so a referenced worker would keep the Node.js main
      // thread alive forever. unref() is the documented way to make a worker
      // non-blocking for process exit; pending async work still keeps the loop
      // alive through emnapi's own waiting-request counter, and worker message
      // delivery is unaffected.
      worker.unref();
      return worker;
    },
    overwriteImports(importObject) {
      importObject.env = {
        ...importObject.env,
        ...importObject.napi,
        ...importObject.emnapi,
        memory: __sharedMemory,
      };
      return importObject;
    },
    beforeInit({ instance }) {
      __napiInstance = instance;
      for (const name of Object.keys(instance.exports)) {
        if (name.startsWith("__napi_register__")) {
          instance.exports[name]();
        }
      }
    },
  }));
  __publishWasiDispose(__napiModule.exports);
  __registerWasiExitListener();
} catch (error) {
  const rollback = {
    active: false,
    error,
    promise: undefined,
    rollback: __rollbackWasiInitialization,
  };
  __wasiRollbackRegistry.set(__wasiRollbackRegistryKey, rollback);
  __runWasiInitializationRollback(rollback);
  throw __annotateWasiInstantiationError(rollback.error);
}
module.exports = __napiModule.exports;
