const fs = require("fs");
const path = require("path");

const packageName = "__PACKAGE_NAME__";
const binaryName = "__ADDON_NAME__";
let nativeBinding = null;
const loadErrors = [];

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (error) {
      loadErrors.push(error);
    }
  }

  for (const platformArchABI of detectPlatformArchABIs()) {
    const binding = requireTuple(platformArchABI);
    if (binding) {
      return binding;
    }
  }
}

function requireTuple(platformArchABI) {
  try {
    return require(
      path.join(__dirname, "zig-out", "node", `${binaryName}.${platformArchABI}.node`),
    );
  } catch (error) {
    loadErrors.push(error);
  }
  try {
    return require(path.join(__dirname, `${binaryName}.${platformArchABI}.node`));
  } catch (error) {
    loadErrors.push(error);
  }
  try {
    return require(optionalPackageName(packageName, platformArchABI));
  } catch (error) {
    loadErrors.push(error);
  }
}

nativeBinding = requireNative();

// WASI flavors generated by the CLI. `wasm32-wasi` is the historical spelling
// of the threaded flavor and keeps its `wasi` loader stem; `wasm32-wasip1` is
// the single-threaded flavor, whose loader needs no cross-origin isolation.
const wasiFlavors = [
  { platformArchABI: "wasm32-wasi", loaderSuffix: "wasi" },
  { platformArchABI: "wasm32-wasip1", loaderSuffix: "wasip1" },
];

// NAPI_RS_FORCE_WASI is a tri-state flag:
//   unset / any other value -> native binding preferred, WASI is only a fallback
//   'true'                  -> force WASI fallback even if native loaded
//   'error'                 -> force WASI and throw if no WASI binding is found
// Treating any non-empty string as truthy (the historical behavior) meant
// NAPI_RS_FORCE_WASI=false, NAPI_RS_FORCE_WASI=0, etc. inadvertently triggered
// the WASI path, causing ENOENT for packages shipped without a WASI loader.
//
// NAPI_RS_WASI_FLAVOR selects one exact generated flavor and implies strict
// WASI loading: it never crosses into another flavor or falls back to native.
const requestedWasiFlavor = process.env.NAPI_RS_WASI_FLAVOR;
const wasiFlavorRequested =
  typeof requestedWasiFlavor === "string" && requestedWasiFlavor.length > 0;
if (
  wasiFlavorRequested &&
  !wasiFlavors.some((flavor) => flavor.platformArchABI === requestedWasiFlavor)
) {
  throw new Error(
    "Unsupported WASI flavor " +
      requestedWasiFlavor +
      "; supported flavors are " +
      wasiFlavors.map((flavor) => flavor.platformArchABI).join(", "),
  );
}

const forceWasiError = process.env.NAPI_RS_FORCE_WASI === "error";
const forceWasi =
  process.env.NAPI_RS_FORCE_WASI === "true" || forceWasiError || wasiFlavorRequested;

if (!nativeBinding || forceWasi) {
  let wasiBinding = null;
  const wasiBindingErrors = [];
  for (const flavor of wasiFlavors) {
    if (wasiBinding) break;
    if (wasiFlavorRequested && flavor.platformArchABI !== requestedWasiFlavor) continue;
    const candidates = [
      path.join(__dirname, "zig-out", "node", `${binaryName}.${flavor.loaderSuffix}.cjs`),
      path.join(__dirname, `${binaryName}.${flavor.loaderSuffix}.cjs`),
      optionalPackageName(packageName, flavor.platformArchABI),
    ];
    for (const candidate of candidates) {
      try {
        wasiBinding = require(candidate);
        nativeBinding = wasiBinding;
        break;
      } catch (error) {
        wasiBindingErrors.push(error);
      }
    }
  }
  if (!wasiBinding && wasiBindingErrors.length > 0) {
    for (const error of wasiBindingErrors) {
      loadErrors.push(error);
    }
  }
  if ((forceWasiError || wasiFlavorRequested) && !wasiBinding) {
    const error = new Error(
      wasiFlavorRequested
        ? `WASI binding for flavor "${requestedWasiFlavor}" not found`
        : "WASI binding not found and NAPI_RS_FORCE_WASI is set to error",
    );
    error.cause = wasiBindingErrors.reduce((cause, current) => {
      current.cause = cause;
      return current;
    });
    throw error;
  }
}

function optionalPackageName(name, platformArchABI) {
  if (name.startsWith("@")) {
    const slash = name.indexOf("/");
    return `${name.slice(0, slash + 1)}${name.slice(slash + 1)}-${platformArchABI}`;
  }
  return `${name}-${platformArchABI}`;
}

function detectPlatformArchABIs() {
  if (process.platform === "android") {
    if (process.arch === "arm64") return ["android-arm64"];
    if (process.arch === "arm") return ["android-arm-eabi"];
  }

  if (process.platform === "darwin") {
    if (process.arch === "x64") return ["darwin-universal", "darwin-x64"];
    if (process.arch === "arm64") return ["darwin-universal", "darwin-arm64"];
  }

  if (process.platform === "freebsd") {
    if (process.arch === "x64") return ["freebsd-x64"];
    if (process.arch === "arm64") return ["freebsd-arm64"];
  }

  if (process.platform === "linux") {
    const abi = isMusl() ? "musl" : "gnu";
    if (process.arch === "x64") return [`linux-x64-${abi}`];
    if (process.arch === "arm64") return [`linux-arm64-${abi}`];
    if (process.arch === "arm") return [`linux-arm-${abi === "musl" ? "musleabihf" : "gnueabihf"}`];
    if (process.arch === "loong64") return [`linux-loong64-${abi}`];
    if (process.arch === "riscv64") return [`linux-riscv64-${abi}`];
    if (process.arch === "ppc64") return ["linux-ppc64-gnu"];
    if (process.arch === "s390x") return ["linux-s390x-gnu"];
  }

  if (process.platform === "openharmony") {
    if (process.arch === "arm64") return ["openharmony-arm64"];
    if (process.arch === "x64") return ["openharmony-x64"];
    if (process.arch === "arm") return ["openharmony-arm"];
  }

  if (process.platform === "win32") {
    if (process.arch === "x64") return ["win32-x64-msvc"];
    if (process.arch === "ia32") return ["win32-ia32-msvc"];
    if (process.arch === "arm64") return ["win32-arm64-msvc"];
  }

  return [];
}

function isMusl() {
  if (process.report && typeof process.report.getReport === "function") {
    return !process.report.getReport().header.glibcVersionRuntime;
  }
  try {
    return fs.readFileSync("/usr/bin/ldd", "utf8").includes("musl");
  } catch {
    return false;
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    const error = new Error(
      "Cannot find native binding. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.",
    );
    error.cause = loadErrors.reduce((err, cur) => {
      cur.cause = err;
      return cur;
    });
    throw error;
  }
  throw new Error("Failed to load native binding");
}

module.exports = nativeBinding;
module.exports.add = nativeBinding.add;
module.exports.hello = nativeBinding.hello;
