/* eslint-disable */
/* auto-generated by zig-napi */

const __nodeFs = require('node:fs')
const __nodePath = require('node:path')
const { WASI: __nodeWASI } = require('node:wasi')
const { Worker } = require('node:worker_threads')

const {
  createOnMessage: __wasmCreateOnMessageForFsProxy,
  getDefaultContext: __emnapiGetDefaultContext,
  instantiateNapiModuleSync: __emnapiInstantiateNapiModuleSync,
} = require('@napi-rs/wasm-runtime')

const __rootDir = __nodePath.parse(process.cwd()).root

const __wasi = new __nodeWASI({
  version: 'preview1',
  env: process.env,
  preopens: {
    [__rootDir]: __rootDir,
  },
})

const __emnapiContext = __emnapiGetDefaultContext()

const __sharedMemory = new WebAssembly.Memory({
  initial: 4000,
  maximum: 65536,
  shared: true,
})

const __wasmCandidates = [
  __nodePath.join(__dirname, 'hello.wasm32-wasi.debug.wasm'),
  __nodePath.join(__dirname, 'hello.wasm32-wasi.wasm'),
  __nodePath.join(__dirname, 'zig-out', 'node', 'hello.wasm32-wasi.debug.wasm'),
  __nodePath.join(__dirname, 'zig-out', 'node', 'hello.wasm32-wasi.wasm'),
]

let __wasmFilePath = __wasmCandidates.find((candidate) => __nodeFs.existsSync(candidate))

if (!__wasmFilePath) {
  try {
    __wasmFilePath = require.resolve('zig-napi-node-example-wasm32-wasi/hello.wasm32-wasi.wasm')
  } catch {
    throw new Error('Cannot find hello.wasm32-wasi.wasm file, and zig-napi-node-example-wasm32-wasi package is not installed.')
  }
}

const {
  instance: __napiInstance,
  module: __wasiModule,
  napiModule: __napiModule,
} = __emnapiInstantiateNapiModuleSync(__nodeFs.readFileSync(__wasmFilePath), {
  context: __emnapiContext,
  asyncWorkPoolSize: (function () {
    const threadsSizeFromEnv = Number(process.env.NAPI_RS_ASYNC_WORK_POOL_SIZE ?? process.env.UV_THREADPOOL_SIZE)
    return threadsSizeFromEnv > 0 ? threadsSizeFromEnv : 4
  })(),
  reuseWorker: true,
  wasi: __wasi,
  onCreateWorker() {
    const worker = new Worker(__nodePath.join(__dirname, 'wasi-worker.mjs'), {
      env: process.env,
    })
    worker.onmessage = ({ data }) => {
      __wasmCreateOnMessageForFsProxy(__nodeFs)(data)
    }

    {
      const kPublicPort = Object.getOwnPropertySymbols(worker).find((symbol) =>
        symbol.toString().includes('kPublicPort')
      )
      if (kPublicPort) {
        worker[kPublicPort].ref = () => {}
      }

      const kHandle = Object.getOwnPropertySymbols(worker).find((symbol) =>
        symbol.toString().includes('kHandle')
      )
      if (kHandle) {
        worker[kHandle].ref = () => {}
      }

      worker.unref()
    }
    return worker
  },
  overwriteImports(importObject) {
    importObject.env = {
      ...importObject.env,
      ...importObject.napi,
      ...importObject.emnapi,
      memory: __sharedMemory,
    }
    return importObject
  },
  beforeInit({ instance }) {
    for (const name of Object.keys(instance.exports)) {
      if (name.startsWith('__napi_register__')) {
        instance.exports[name]()
      }
    }
  },
})

module.exports = __napiModule.exports
module.exports.add = __napiModule.exports.add
module.exports.hello = __napiModule.exports.hello
module.exports.requestedNapiVersion = __napiModule.exports.requestedNapiVersion
module.exports.fibonacciAsync = __napiModule.exports.fibonacciAsync
module.exports.countAsyncProgress = __napiModule.exports.countAsyncProgress
