/* auto-generated by zig-addon */
/* eslint-disable */

export interface CountProgress {
  current: number;
  total: number;
}

export declare function add(left: number, right: number): number;
export declare function hello(): string;
export declare function requestedNapiVersion(): number;
export declare function fibonacciAsync(n: number): Promise<number>;
export declare function countAsyncProgress(
  total: number,
  onEvent?: (event: CountProgress) => void,
): Promise<number>;
