/* auto-generated by zig-addon */
/* eslint-disable */
export declare function add(left: number, right: number): number;
export declare function hello(): string;
export declare function requestedNapiVersion(): number;
