// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by zig-napi */

const fs = require('fs')
const path = require("path");

let nativeBinding = null;
const loadErrors = [];

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (error) {
      loadErrors.push(error);
    }
  }

  for (const platformArchABI of detectPlatformArchABIs()) {
    const binding = requireTuple(platformArchABI);
    if (binding) {
      return binding;
    }
  }
}

function requireTuple(platformArchABI) {
  try {
    return require(path.join(__dirname, "zig-out", "node", `hello.${platformArchABI}.node`));
  } catch (error) {
    loadErrors.push(error);
  }
  try {
    return require(path.join(__dirname, `hello.${platformArchABI}.node`));
  } catch (error) {
    loadErrors.push(error);
  }
  try {
    return require(optionalPackageName("zig-napi-node-example", platformArchABI));
  } catch (error) {
    loadErrors.push(error);
  }
}

nativeBinding = requireNative();

// NAPI_RS_FORCE_WASI is a tri-state flag:
//   unset / any other value -> native binding preferred, WASI is only a fallback
//   'true'                  -> force WASI fallback even if native loaded
//   'error'                 -> force WASI and throw if no WASI binding is found
const forceWasi =
  process.env.NAPI_RS_FORCE_WASI === "true" || process.env.NAPI_RS_FORCE_WASI === "error";

// WASI flavors, the same two the CLI generates loaders for:
//   'wasi'   -> threaded, shared memory, async work on the JavaScript worker pool
//   'wasip1' -> single-threaded, unshared memory, no workers
// NAPI_RS_WASI_FLAVOR pins one of them; unset tries the threaded flavor first and
// falls back to the single-threaded one. A pinned flavor never falls back to the
// other flavor, and an unknown value is an error rather than a silent default.
const WASI_FLAVOR_SUFFIXES = { wasi: "wasi", wasip1: "wasip1" };
const wasiFlavorEnv = process.env.NAPI_RS_WASI_FLAVOR;
let wasiFlavorOrder;
if (wasiFlavorEnv === undefined || wasiFlavorEnv === "") {
  wasiFlavorOrder = ["wasi", "wasip1"];
} else if (Object.prototype.hasOwnProperty.call(WASI_FLAVOR_SUFFIXES, wasiFlavorEnv)) {
  wasiFlavorOrder = [wasiFlavorEnv];
} else {
  throw new Error(
    `NAPI_RS_WASI_FLAVOR must be one of ${Object.keys(WASI_FLAVOR_SUFFIXES).join(", ")} ` +
      `(got ${JSON.stringify(wasiFlavorEnv)})`,
  );
}

function requireWasiFlavor(flavor) {
  const suffix = WASI_FLAVOR_SUFFIXES[flavor];
  const candidates = [
    path.join(__dirname, "zig-out", "node", `hello.${suffix}.cjs`),
    path.join(__dirname, `hello.${suffix}.cjs`),
    `zig-napi-node-example-wasm32-${suffix}`,
  ];
  let lastError = null;
  for (const candidate of candidates) {
    try {
      return require(candidate);
    } catch (error) {
      if (!lastError) {
        lastError = error;
      } else {
        lastError.cause = error;
      }
    }
  }
  throw lastError ?? new Error(`no WASI ${flavor} binding available`);
}

if (!nativeBinding || forceWasi) {
  let wasiBinding = null;
  let wasiBindingError = null;
  for (const flavor of wasiFlavorOrder) {
    try {
      wasiBinding = requireWasiFlavor(flavor);
      nativeBinding = wasiBinding;
      break;
    } catch (error) {
      if (!wasiBindingError) {
        wasiBindingError = error;
      } else {
        wasiBindingError.cause = error;
      }
      loadErrors.push(error);
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === "error" && !wasiBinding) {
    const error = new Error(
      `WASI binding not found (flavor${wasiFlavorOrder.length > 1 ? "s" : ""} ` +
        `${wasiFlavorOrder.join(", ")} are built by ` +
        "`zig-napi build --target wasm32-wasip1[-threads]`) and NAPI_RS_FORCE_WASI is set to error",
    );
    error.cause = wasiBindingError;
    throw error;
  }
}

function optionalPackageName(name, platformArchABI) {
  if (name.startsWith("@")) {
    const slash = name.indexOf("/");
    return `${name.slice(0, slash + 1)}${name.slice(slash + 1)}-${platformArchABI}`;
  }
  return `${name}-${platformArchABI}`;
}

function detectPlatformArchABIs() {
  if (process.platform === "android") {
    if (process.arch === "arm64") return ["android-arm64"];
    if (process.arch === "arm") return ["android-arm-eabi"];
  }

  if (process.platform === "darwin") {
    if (process.arch === "x64") return ["darwin-universal", "darwin-x64"];
    if (process.arch === "arm64") return ["darwin-universal", "darwin-arm64"];
  }

  if (process.platform === "freebsd") {
    if (process.arch === "x64") return ["freebsd-x64"];
    if (process.arch === "arm64") return ["freebsd-arm64"];
  }

  if (process.platform === "linux") {
    const abi = isMusl() ? "musl" : "gnu";
    if (process.arch === "x64") return [`linux-x64-${abi}`];
    if (process.arch === "arm64") return [`linux-arm64-${abi}`];
    if (process.arch === "arm") return [`linux-arm-${abi === "musl" ? "musleabihf" : "gnueabihf"}`];
    if (process.arch === "loong64") return [`linux-loong64-${abi}`];
    if (process.arch === "riscv64") return [`linux-riscv64-${abi}`];
    if (process.arch === "ppc64") return ["linux-ppc64-gnu"];
    if (process.arch === "s390x") return ["linux-s390x-gnu"];
  }

  if (process.platform === "openharmony") {
    if (process.arch === "arm64") return ["openharmony-arm64"];
    if (process.arch === "x64") return ["openharmony-x64"];
    if (process.arch === "arm") return ["openharmony-arm"];
  }

  if (process.platform === "win32") {
    if (process.arch === "x64") return ["win32-x64-msvc"];
    if (process.arch === "ia32") return ["win32-ia32-msvc"];
    if (process.arch === "arm64") return ["win32-arm64-msvc"];
  }

  return [];
}

function isMusl() {
  if (process.report && typeof process.report.getReport === "function") {
    return !process.report.getReport().header.glibcVersionRuntime;
  }
  try {
    return fs.readFileSync("/usr/bin/ldd", "utf8").includes("musl");
  } catch {
    return false;
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    const error = new Error(
      "Cannot find native binding. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try npm i again after removing both package-lock.json and node_modules directory.",
    );
    error.cause = loadErrors.reduce((err, cur) => {
      cur.cause = err;
      return cur;
    });
    throw error;
  }
  throw new Error("Failed to load native binding");
}

module.exports = nativeBinding;
module.exports.add = nativeBinding.add;
module.exports.hello = nativeBinding.hello;
module.exports.requestedNapiVersion = nativeBinding.requestedNapiVersion;
module.exports.fibonacciAsync = nativeBinding.fibonacciAsync;
module.exports.countAsyncProgress = nativeBinding.countAsyncProgress;
