"use strict";

const fs = require("node:fs");
const path = require("node:path");
const ts = require("typescript");
const { generateTypeDef } = require("@napi-rs/cli");
const { rebaseDeclarationSpecifiers } = require("./declarations.cjs");

// Cargo switches cannot be forwarded to `zig build`: reject them before a
// build or write, and keep the user-provided Zig arguments after `--` intact.
const cargoOptions = [
  "--bin",
  "--package",
  "-p",
  "--profile",
  "--use-cross",
  "--use-napi-cross",
  "--features",
  "-F",
  "--all-features",
  "--no-default-features",
  "--ohos-sign",
  "--no-ohos-sign",
];
function validate(flags, args) {
  for (const arg of args) {
    if (cargoOptions.some((option) => arg === option || arg.startsWith(option + "=")))
      throw new Error(
        `${arg.split("=")[0]} is a Cargo/OHOS option, outside this Node.js/WASI Zig CLI; use --cwd/--target or Zig build options after --`,
      );
  }
  const formats = [
    flags.format,
    flags.esm ? "esm" : undefined,
    flags.commonjs ? "commonjs" : undefined,
  ].filter(Boolean);
  if (formats.some((f) => !["esm", "commonjs"].includes(f)) || new Set(formats).size > 1)
    throw new Error("Choose one build format: esm or commonjs");
  if (flags.manifestPath && !/\.zig(?:\.zon)?$/.test(flags.manifestPath))
    throw new Error(
      "--manifest-path must point to a Zig build.zig or build.zig.zon file, not Cargo.toml",
    );
}

function renderEnums(source, constEnum, runtimeStringEnum) {
  if (constEnum !== false) return source;
  const tree = ts.createSourceFile("index.d.ts", source, ts.ScriptTarget.Latest, true);
  const edits = [];
  const visit = (node) => {
    if (ts.isEnumDeclaration(node)) {
      const strings =
        node.members.length > 0 &&
        node.members.every((m) => m.initializer && ts.isStringLiteral(m.initializer));
      if (strings && !runtimeStringEnum) {
        const exported = node.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword)
          ? "export "
          : "";
        edits.push([
          node.getStart(tree),
          node.end,
          `${exported}type ${node.name.text} = ${node.members.map((m) => m.initializer.getText(tree)).join(" | ")};`,
        ]);
      } else {
        for (const modifier of node.modifiers || [])
          if (modifier.kind === ts.SyntaxKind.ConstKeyword)
            edits.push([modifier.getStart(tree), modifier.end, ""]);
      }
    } else ts.forEachChild(node, visit);
  };
  visit(tree);
  for (const [start, end, replacement] of edits.sort((a, b) => b[0] - a[0]))
    source = source.slice(0, start) + replacement + source.slice(end);
  return source;
}

function readDeclarationSource(cwd) {
  const sourcePath = path.join(cwd, "index.d.ts");
  if (!fs.existsSync(sourcePath)) return "";
  const source = fs.readFileSync(sourcePath, "utf8");
  const cachePath = path.join(cwd, ".zig-cache", "zig-napi-declarations.json");
  let cache;
  try {
    cache = JSON.parse(fs.readFileSync(cachePath, "utf8"));
  } catch {}
  return cache?.rendered === source ? cache.source : source;
}

async function declarations(cwd, flags, config, outputDir, binding) {
  if (!config.typeDef) return;
  const sourcePath = path.join(cwd, "index.d.ts");
  if (!fs.existsSync(sourcePath)) return;
  let source = readDeclarationSource(cwd);
  const cachePath = path.join(cwd, ".zig-cache", "zig-napi-declarations.json");
  const original = source;
  source = source
    .replace(/^\/\* auto-generated by (?:zig-addon|zig-napi|NAPI-RS) \*\/\r?\n/, "")
    .replace(/^\/\* eslint-disable \*\/\r?\n/, "")
    .replace(
      /^\/\* zig-napi binding target \*\/\nexport declare const __napiBindingTarget:[^\n]*\n?/gm,
      "",
    );
  source = renderEnums(
    source,
    flags.constEnum ?? config.constEnum,
    flags.runtimeStringEnum ?? config.runtimeStringEnum,
  );
  // The upstream public API owns header precedence, header files and defaults.
  // Zig emits TypeScript rather than napi-derive's intermediate Rust records.
  const { header } = await generateTypeDef({
    cwd,
    typeDefDir: path.join(cwd, ".zig-cache", "zig-napi-no-rust-types"),
    noDtsHeader: flags.dtsHeader === false,
    dtsHeader: typeof flags.dtsHeader === "string" ? flags.dtsHeader : undefined,
    configDtsHeader: config.dtsHeader,
    configDtsHeaderFile: config.dtsHeaderFile,
  });
  const tree = ts.createSourceFile("index.d.ts", header + source, ts.ScriptTarget.Latest, true);
  const hasTarget = tree.statements.some(
    (s) =>
      ts.isVariableStatement(s) &&
      s.declarationList.declarations.some(
        (d) => ts.isIdentifier(d.name) && d.name.text === "__napiBindingTarget",
      ),
  );
  if (binding && !hasTarget && !tree.statements.some(ts.isExportAssignment))
    source =
      source.trimEnd() +
      '\n/* zig-napi binding target */\nexport declare const __napiBindingTarget: "native" | "wasm32-wasi" | "wasm32-wasip1";\n';
  const rendered = header + source;
  const destination = path.resolve(outputDir, flags.dts || "index.d.ts");
  fs.mkdirSync(path.dirname(destination), { recursive: true });
  const rebased = rebaseDeclarationSpecifiers(rendered, sourcePath, destination);
  fs.writeFileSync(destination, rebased);
  fs.mkdirSync(path.dirname(cachePath), { recursive: true });
  fs.writeFileSync(
    cachePath,
    JSON.stringify({
      source: original,
      rendered: destination === sourcePath ? rebased : fs.readFileSync(sourcePath, "utf8"),
    }),
  );
  return destination;
}

function rebaseNativeBinding(file, outputDir, binaryName) {
  if (path.dirname(file) === outputDir) return;
  let source = fs.readFileSync(file, "utf8");
  const tree = ts.createSourceFile(file, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.JS);
  const edits = [];
  // writeJsBinding already rebases WASI paths; its native candidates are still
  // relative to the loader. Keep the public generator and fix just those paths.
  const visit = (node) => {
    if (
      ts.isStringLiteral(node) &&
      node.text.startsWith(`./${binaryName}.`) &&
      node.text.endsWith(".node")
    ) {
      let specifier = path
        .relative(path.dirname(file), path.join(outputDir, node.text))
        .split(path.sep)
        .join("/");
      if (!specifier.startsWith(".")) specifier = "./" + specifier;
      edits.push([node.getStart(tree), node.end, JSON.stringify(specifier)]);
    }
    ts.forEachChild(node, visit);
  };
  visit(tree);
  for (const [start, end, replacement] of edits.sort((a, b) => b[0] - a[0]))
    source = source.slice(0, start) + replacement + source.slice(end);
  fs.writeFileSync(file, source);
}

module.exports = {
  cargoOptions,
  validate,
  renderEnums,
  declarations,
  readDeclarationSource,
  rebaseNativeBinding,
};
