/* auto-generated by zig-addon */
/* eslint-disable */

export interface Stats {
  alloc_calls: number
  free_calls: number
  active_allocations: number
  active_bytes: number
}


export declare function allocator_kind(): string
export declare function allocator_stats(): Stats
export declare function custom_allocation_roundtrip(len: number): boolean
export declare function make_js_owned_buffer(len: number): Buffer
export declare function make_copied_buffer(): Buffer
export declare function input_sum(input: Buffer): number
