/* auto-generated by zig-addon */
/* eslint-disable */

export interface FullField {
  name: string
  age: number
  is_student: boolean
}

export interface OptionalField {
  name: string
  age?: number
  is_student?: boolean
}

export interface NullableField {
  name?: string
}

export declare class TestClass {
  constructor(name: string, age: number)
  name: string
  age: number
}

export declare class TestWithInitClass {
  constructor(age: number, name: string)
  name: string
  age: number
  static readonly hello: string
}

export declare class TestWithoutInitClass {
  private constructor()
  name: string
  age: number
  static readonly hello: string
}

export declare class TestFactoryClass {
  constructor(name: string, age: number)
  name: string
  age: number
  static initWithFactory(age: number, name: string): TestFactoryClass
  format(): string
}


export declare function test_i32(left: number, right: number): number
export declare function test_f32(left: number, right: number): number
export declare function test_u32(left: number, right: number): number
export declare function hello(name: string): string
export declare const text: string
export declare function throw_error(): void
export declare function fib(n: number): void
export declare function fib_async(n: number): Promise<void>
export declare function get_and_return_array(array: Array<number>): Array<number>
export declare function get_named_array(array: [number, boolean, string]): [number, boolean, string]
export declare function get_arraylist(array: Array<number>): Array<number>
export declare function get_object(config: FullField): FullField
export declare function get_object_optional(config: OptionalField): OptionalField
export declare function get_optional_object_and_return_optional(config: OptionalField): OptionalField
export declare function get_nullable_object(config: NullableField): NullableField
export declare function return_nullable(): NullableField
export declare function call_function(cb: (arg0: number, arg1: number) => number): number
export declare function basic_function(left: number, right: number): number
export declare function create_function(): (left: number, right: number) => number
export declare function call_function_with_reference(cb: (arg0: number, arg1: number) => number): number
export declare function call_thread_safe_function(tsfn: (err: Error | null, arg0: number, arg1: number) => void): void
export declare function test_hilog(): void
export declare function create_buffer(): Buffer
export declare function get_buffer(buf: Buffer): number
export declare function get_buffer_as_string(buf: Buffer): string
export declare function create_arraybuffer(): ArrayBuffer
export declare function get_arraybuffer(buf: ArrayBuffer): number
export declare function get_arraybuffer_as_string(buf: ArrayBuffer): string
export declare function create_uint8_typedarray(): Uint8Array
export declare function get_uint8_typedarray_length(array: Uint8Array): number
export declare function sum_float32_typedarray(array: Float32Array): number
export declare function create_dataview(): DataView
export declare function get_dataview_length(view: DataView): number
export declare function get_dataview_first_byte(view: DataView): number
export declare function get_dataview_uint32_le(view: DataView): number
