/* auto-generated by zig-addon */
/* eslint-disable */

export interface ExternalResult {
  value: string
  copied: boolean
}

export interface parityEnvironment__struct_30410 {
  stored: boolean
  replacement_rejected: boolean
  async_removed: boolean
}

export interface MetadataObject {
  readonly count: number
  missing: number | null
}

export interface TaggedPayload__struct_30932 {
  count: number
}

export interface TaggedPayload__struct_30933 {
  count: number
}

export interface parityThis__struct_31517 {
  base: number
}

export interface parityStringLengths__struct_35627 {
  utf8: number
  utf16: number
  latin1: number
}

export interface parityObject__struct_35851 {
  x: number
  __proto__: number
}

export interface FibProgress {
  current: number
  total: number
}

export interface FileReadSummary {
  path: string
  bytes: number
  text: string
}

export interface ParallelReadInput {
  first_path: string
  second_path: string
  preview_bytes: number
}

export interface ParallelReadSummary {
  first_bytes: number
  second_bytes: number
  total_bytes: number
  preview: string
}

export interface AsyncMathInput {
  left: number
  right: number
  scale: number
}

export interface AsyncMathResult {
  sum: number
  product: number
  scaled_sum: number
}

export interface CountProgress {
  current: number
  total: number
}

export interface AbortSignal {
  aborted: boolean
  reason?: any
  onabort: null | ((this: AbortSignal, event: any) => void)
  addEventListener(name: string, listener: (this: AbortSignal, event: any) => any): void
  removeEventListener(name: string, listener: (this: AbortSignal, event: any) => any): void
  throwIfAborted?(): void
}

export interface FullField {
  name: string
  age: number
  is_student: boolean
}

export interface OptionalField {
  name: string
  age?: number
  is_student?: boolean
}

export interface NullableField {
  name?: string
}

// Opaque host buffer; use the native buffer API to access its bytes.
export type Buffer = object

export interface MessagePayload {
  title: string
  count: number
}

export declare const enum Color {
  Red = 1,
  Green = 2,
  Blue = 4,
}

export declare const enum StringColor {
  Red = 'Red',
  Green = 'Green',
  Blue = 'Blue',
}

declare const __napiExternalBrand: unique symbol
export interface ExternalObject<T> {
  readonly [__napiExternalBrand]: T
}

export interface ExternalPoint {
  x: number
  y: number
}


export declare function parityReadable(stream: ReadableStream<number>): ReadableStreamDefaultReader<number>
export declare function parityRead(reader: ReadableStreamDefaultReader<number>): Promise<IteratorResult<number>>
export declare function parityReaderCancel(reader: ReadableStreamDefaultReader<number>, reason: unknown): Promise<unknown>
export declare function parityReaderRelease(reader: ReadableStreamDefaultReader<number>): void
export declare function parityWritable(stream: WritableStream<number>): WritableStreamDefaultWriter<number>
export declare function parityWrite(writer: WritableStreamDefaultWriter<number>, value: number): Promise<unknown>
export declare function parityWriterClose(writer: WritableStreamDefaultWriter<number>): Promise<unknown>
export declare function parityWriterAbort(writer: WritableStreamDefaultWriter<number>, reason: unknown): Promise<unknown>
export declare function parityWriterRelease(writer: WritableStreamDefaultWriter<number>): void
export declare function parityNativeReadable(count: number): ReadableStream<number>
export declare function parityFeatureVersion(): number
export declare function parityExternalLatin1(value: string): ExternalResult
export declare function parityExternalUtf16(value: string): ExternalResult
export declare function parityEnvironment(): parityEnvironment__struct_30410
export declare function parityDate(date: Date): Date
export declare function parityMetadataObject(value: MetadataObject): MetadataObject
export declare namespace parityTools {
export type MetadataSchema = MetadataObject
}
export declare function parityTagged(value: { kind: 'first'; data: TaggedPayload__struct_30932 } | { kind: 'second'; data: TaggedPayload__struct_30933 } | { kind: 'text'; data: string }): { kind: 'first'; data: TaggedPayload__struct_30932 } | { kind: 'second'; data: TaggedPayload__struct_30933 } | { kind: 'text'; data: string }
export declare function paritySymbolFor(key: string): symbol
export declare function paritySymbol(symbol: symbol): Record<string, unknown>
export declare function parityThis(this: parityThis__struct_31517, value: number): number
export declare function parityAsyncGenerator(count: number): AsyncIterableIterator<number>
export declare function parityAwaitPromise(value: Promise<number>): Promise<number>
export declare function parityPromise(value: Promise<number>, callback: (arg: number) => number): Promise<number>
export declare function parityPromiseCatch(value: Promise<unknown>, callback: (arg: unknown) => number): Promise<unknown>
export declare function parityPromiseFinally(value: Promise<unknown>, callback: () => void): Promise<unknown>
export declare function parityAsyncMap(value: Record<string, string>): Promise<Record<string, string>>
export declare function parityAsyncJson(value: unknown): Promise<unknown>
export declare function parityMap(value: Record<string, string>): Record<string, string>
export declare function paritySet(value: Set<number>): Set<number>
export declare function parityJson(value: unknown): unknown
export declare function parityIterator(count: number): IterableIterator<number>
export declare function parityIteratorSum(value: IterableIterator<number>): number
export declare function parityAsyncIteratorNext(value: AsyncIterableIterator<number>): Promise<IteratorResult<number>>
export declare function parityTsfnAsync(callback: (arg: number) => number, value: number): Promise<unknown>
export declare function parityTsfnPromise(callback: (arg: number) => Promise<unknown>, value: number): Promise<unknown>
export declare function parityTsfnBuilder(callback: (arg: number) => number): Record<string, unknown>
export declare function parityTsfnBlocking(callback: (arg: number) => void): void
export declare function parityTsfnAbort(callback: (arg: number) => void): boolean
export declare function parityClassInstance(instance: ParityCounter, amount: number): number
export declare class ParityFactory {
  private constructor()
  value: number
  static create(arg: number): ParityFactory
}

export declare function parityFactoryInstance(instance: ParityFactory): number
export declare class ParityCounter {
  constructor(arg: number)
  value: number
}

export declare function paritySharedThread(object: Record<string, unknown>): Record<string, unknown>
export declare function parityWeakClosure(object: Record<string, unknown>): () => Record<string, unknown> | undefined | null
export declare function parityShared(object: Record<string, unknown>): Record<string, unknown>
export declare namespace parityTools {
export class RenamedCounter {
  constructor(arg: number)
  value: number
}

}
export declare function parityNamespaced(instance: parityTools.RenamedCounter): number
export declare class MetadataCounter {
  constructor(arg: number)
  readonly count: number
  add(arg: number): number
  get double(): number
  set double(value: number)
}

export declare function parityStringLengths(value: string): parityStringLengths__struct_35627
export declare function parityLatin1(value: string): string
export declare function parityObject(): parityObject__struct_35851
export declare function parityApply(callback: (arg: number) => number, receiver: Record<string, unknown>, value: number): number
export declare function parityBind(callback: (arg: number) => number, receiver: Record<string, unknown>): (arg: number) => number
export declare function parityConstruct(callback: (arg: number) => void, value: number): Record<string, unknown>
export declare namespace parityTools {
export function functionName(arg: () => void): string
}
export declare function parityClosure(initial: number): (arg: number) => number
export declare function parityScope(): unknown
export declare function parityScript(source: string): unknown
export declare function test_i32(left: number, right: number): number
export declare function test_f32(left: number, right: number): number
export declare function test_u32(left: number, right: number): number
export declare const custom_add: (left: Number, right: Number) => Number
export declare function hello(name: string): string
export declare function raw_string_len(value: string): number
export declare function copied_string_len(value: string): number
export declare const text: string
export declare const custom_text: String
export declare function custom_string(name: string): String
export declare function throw_error(): void
export declare function result_ok(): number
export declare function result_error(): number
export declare function result_void_ok(): void
export declare function result_after_try(input: boolean): number
export declare function throw_zig_error(): void
export declare function throw_zig_error_value(): number
export declare function fib(n: number): void
export declare function fib_async(n: number): Promise<number>
export declare function fib_async_progress(n: number, onEvent?: (event: FibProgress) => void): Promise<number>
export declare function read_file_async(path: string): Promise<string>
export declare function read_file_summary_async(path: string): Promise<FileReadSummary>
export declare function parallel_read_files_async(input: ParallelReadInput): Promise<ParallelReadSummary>
export declare function async_math_single(input: AsyncMathInput): Promise<AsyncMathResult>
export declare function async_void_thread(): Promise<void>
export declare function async_fail_thread(message: string): Promise<void>
export declare function count_async_progress_thread(total: number, onEvent?: (event: CountProgress) => void): Promise<number>
export declare function event_mode_progress_async(total: number, onEvent?: (event: CountProgress) => void): Promise<number>
export declare function abortable_count_async(total: number, signal: AbortSignal): Promise<number>
export declare function get_and_return_array(array: Array<number>): Array<number>
export declare function get_named_array(array: [number, boolean, string]): [number, boolean, string]
export declare function get_arraylist(array: Array<number>): Array<number>
export declare function raw_array_sum(array: Array<unknown>): number
export declare function raw_array_create(): Array<unknown>
export declare function get_object(config: FullField): FullField
export declare function get_object_optional(config: OptionalField): OptionalField
export declare function get_optional_object_and_return_optional(config: OptionalField): OptionalField
export declare function get_nullable_object(config: NullableField): NullableField
export declare function return_nullable(): NullableField
export declare function raw_object_read(config: Record<string, unknown>, key: string): number
export declare function raw_object_create(key: string, value: number): Record<string, unknown>
export declare function call_function(cb: (arg0: number, arg1: number) => number): number
export declare function basic_function(left: number, right: number): number
export declare function create_function(): (left: number, right: number) => number
export declare function call_function_with_reference(cb: (arg0: number, arg1: number) => number): number
export declare function call_thread_safe_function(tsfn: (err: Error | null, arg0: number, arg1: number) => number): void
export declare class TestClass {
  constructor(name: string, age: number)
  name: string
  age: number
}

export declare class TestWithInitClass {
  constructor(age: number, name: string)
  name: string
  age: number
  static readonly hello: string
}

export declare class TestWithoutInitClass {
  private constructor()
  name: string
  age: number
  static readonly hello: string
}

export declare class TestFactoryClass {
  constructor(name: string, age: number)
  name: string
  age: number
  static initWithFactory(age: number, name: string): TestFactoryClass
  format(): string
}

export declare function test_hilog(): void
export declare function create_buffer(): Buffer
export declare function create_empty_buffer_new(): Buffer
export declare function create_empty_buffer_copy(): Buffer
export declare function create_empty_external_buffer(): Buffer
export declare function get_buffer(buf: Buffer): number
export declare function get_buffer_as_string(buf: Buffer): string
export declare function create_arraybuffer(): ArrayBuffer
export declare function create_empty_arraybuffer_new(): ArrayBuffer
export declare function create_empty_arraybuffer_copy(): ArrayBuffer
export declare function create_empty_external_arraybuffer(): ArrayBuffer
export declare function get_arraybuffer(buf: ArrayBuffer): number
export declare function get_arraybuffer_as_string(buf: ArrayBuffer): string
export declare function create_uint8_typedarray(): Uint8Array
export declare function get_uint8_typedarray_length(array: Uint8Array): number
export declare function sum_float32_typedarray(array: Float32Array): number
export declare function create_dataview(): DataView
export declare function get_dataview_length(view: DataView): number
export declare function get_dataview_first_byte(view: DataView): number
export declare function get_dataview_uint32_le(view: DataView): number
export declare function union_identity(value: number | string): number | string
export declare function make_union(is_number: boolean): number | string
export declare function union_kind(value: number | string): string
export declare function object_or_text_identity(value: MessagePayload | string): MessagePayload | string
export declare function make_object_or_text(as_object: boolean): MessagePayload | string
export declare function object_or_array_identity(value: MessagePayload | Array<number>): MessagePayload | Array<number>
export declare function tuple_or_text_identity(value: [number, boolean, string] | string): [number, boolean, string] | string
export declare function flip_flag_or_increment(value: boolean | number): boolean | number
export declare function color_or_text_identity(value: Color | string): Color | string
export declare function favorite_color_or_text(use_color: boolean): Color | string
export declare function maybe_text_or_count_identity(value: string | undefined | null | number): string | undefined | null | number
export declare function make_maybe_text_or_count(as_text: boolean): string | undefined | null | number
export declare function buffer_or_text_identity(value: Buffer | string): Buffer | string
export declare function make_buffer_or_text(use_buffer: boolean): Buffer | string
export declare function arraybuffer_or_array_identity(value: ArrayBuffer | Array<number>): ArrayBuffer | Array<number>
export declare function make_arraybuffer_or_array(use_arraybuffer: boolean): ArrayBuffer | Array<number>
export declare function payload_or_color_identity(value: MessagePayload | Color): MessagePayload | Color
export declare function make_payload_or_color(use_payload: boolean): MessagePayload | Color
export declare function payload_or_string_color_identity(value: MessagePayload | StringColor): MessagePayload | StringColor
export declare function make_payload_or_string_color(use_payload: boolean): MessagePayload | StringColor
export declare function enum_identity(color: Color): Color
export declare function favorite_color(): Color
export declare function is_primary(color: Color): boolean
export declare function string_enum_identity(color: StringColor): StringColor
export declare function favorite_string_color(): StringColor
export declare function create_external(value: number): ExternalObject<number>
export declare function create_external_with_size_hint(value: number): ExternalObject<number>
export declare function create_external_pair(value: number): Array<ExternalObject<number>>
export declare function create_misaligned_external(): unknown | undefined | null
export declare function get_external(external: ExternalObject<number>): number
export declare function get_external_size_hint(external: ExternalObject<number>): number
export declare function mutate_external(external: ExternalObject<number>, value: number): void
export declare function create_external_point(x: number, y: number): ExternalObject<ExternalPoint>
export declare function get_external_point(external: ExternalObject<ExternalPoint>): ExternalPoint
export declare function mutate_external_point(external: ExternalObject<ExternalPoint>, x: number, y: number): void
export declare function external_either_kind(value: ExternalObject<number> | ExternalObject<ExternalPoint>): number
export declare function external_either_value(value: ExternalObject<number> | ExternalObject<ExternalPoint>): number
export declare function reset_detached_external_deinit_count(): void
export declare function detached_external_deinit_count(): number
export declare function deinit_detached_external(): number
