name: Build test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test on ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup OpenHarmony SDK
        uses: openharmony-rs/setup-ohos-sdk@v0.1
        id: setup-ohos
        with:
          version: '5.0.0'

      - name: Setup Zig for OpenHarmony
        uses: openharmony-zig/setup-zig-ohos@v0.1.0
        id: setup-zig

      - name: Build
        run: |
          pushd examples/basic && zig build && popd
          pushd examples/init && zig build && popd